module.exports = {
  FOLLOW_UP_DELAY_MS: 2 * 60 * 60 * 1000,
  OPENAI_MAX_TOKENS: 300,
  OPENAI_STREAM_TOKENS: 150,
  OPENAI_TEMPERATURE: 0.7,
  OPENAI_MODEL: "gpt-4o-mini",
  OPENAI_TIMEOUT_MS: 30000,
  CONVERSATION_HISTORY_LIMIT: 10,
  STREAM_HISTORY_LIMIT: 8,
  MAX_STREAM_MESSAGE_LENGTH: 1000,
  PAYSTACK_TIMEOUT_MS: 10000,
  WHATSAPP_TIMEOUT_MS: 8000,
  MAX_SYSTEM_PROMPT_LENGTH: 2000,
  PURCHASE_KEYWORDS: [
    "buy",
    "order",
    "purchase",
    "want to get",
    "how much",
    "price",
    "cost",
    "i'll take",
    "checkout",
    "pay",
    "payment",
    "deliver",
    "shipping",
    "i want",
  ],
  VALID_ORDER_STATUSES: [
    "pending",
    "confirmed",
    "processing",
    "delivered",
    "cancelled",
  ],
  VALID_PERSONA_TONES: ["friendly", "professional", "playful", "formal"],
  VALID_PLAN_IDS: ["starter", "pro"],
  ALLOWED_PROFILE_FIELDS: [
    "business_name",
    "phone_number",
    "industry",
    "currency",
    "timezone",
    "full_name",
    "email",
  ],
  ALLOWED_AI_FIELDS: [
    "persona_name",
    "persona_tone",
    "system_prompt",
    "auto_mode",
    "auto_followup",
    "language",
  ],
};
